/**
 * Knowledge Sync System Types
 *
 * Database schema for automatic knowledge synchronization from websites
 */

// ============================================
// FAQ Extended Schema
// ============================================

export type FAQSource = 'manual' | 'website' | 'document' | 'website_auto'

export interface ExtendedFAQ {
  id: string
  question: string
  answer: string
  source: FAQSource
  confirmed: boolean

  // Website sync fields
  websiteLastSeen?: Date
  possiblyOutdated?: boolean
  autoGenerated?: boolean
  websiteUrl?: string // URL where this FAQ was found

  // Metadata
  createdAt: Date
  updatedAt: Date
  createdBy?: string // userId or 'system'
}

// ============================================
// Website Sync Jobs
// ============================================

export type SyncJobStatus = 'pending' | 'running' | 'completed' | 'failed'

export interface WebsiteSyncJob {
  id: string
  companyId: string
  websiteUrl: string
  status: SyncJobStatus

  // Results
  newFaqsFound: number
  conflictsFound: number
  faqsUpdated: number
  faqsMarkedOutdated: number

  // Timing
  startedAt: Date
  completedAt?: Date
  duration?: number // milliseconds

  // Error tracking
  error?: string
  errorDetails?: string

  // Hash of scraped content for change detection
  contentHash?: string
  previousContentHash?: string
}

// ============================================
// Knowledge Conflicts
// ============================================

export type ConflictStatus = 'pending' | 'resolved_keep_current' | 'resolved_use_website' | 'resolved_merged' | 'dismissed'

export interface KnowledgeConflict {
  id: string
  companyId: string
  faqId: string

  // Current value (from manual/existing)
  currentQuestion: string
  currentAnswer: string
  currentSource: FAQSource

  // New value from website
  websiteQuestion: string
  websiteAnswer: string
  websiteUrl: string

  // Similarity score (0-1)
  similarityScore: number

  // Status
  status: ConflictStatus

  // Resolution
  resolvedBy?: string // userId
  resolvedAt?: Date
  resolutionNote?: string

  // Timestamps
  createdAt: Date
  updatedAt: Date
}

// ============================================
// Sync Configuration
// ============================================

export interface SyncConfiguration {
  companyId: string
  websiteUrl: string
  enabled: boolean

  // Sync frequency
  syncIntervalHours: number // default: 1

  // Last sync info
  lastSyncAt?: Date
  lastSyncJobId?: string

  // Settings
  autoApproveWebsiteFaqs: boolean // default: false
  notifyOnConflicts: boolean // default: true
  notifyOnNewFaqs: boolean // default: true

  // Pages to scrape
  additionalUrls?: string[] // Extra pages to scrape besides auto-detected
  excludedPaths?: string[] // Paths to ignore

  // Created/Updated
  createdAt: Date
  updatedAt: Date
}

// ============================================
// Extracted Info from Website
// ============================================

export interface ExtractedFAQInfo {
  question: string
  answer: string
  sourceUrl: string
  confidence: number // AI confidence score 0-1
  category?: string
}

export interface WebsiteAnalysisResult {
  faqs: ExtractedFAQInfo[]
  businessInfo?: {
    name?: string
    description?: string
    openingHours?: string
    phone?: string
    email?: string
    address?: string
  }
  contentHash: string
  scrapedAt: Date
}

// ============================================
// Sync Result Summary
// ============================================

export interface SyncResultSummary {
  success: boolean
  jobId: string

  // Counts
  totalFaqsOnWebsite: number
  newFaqsCreated: number
  conflictsCreated: number
  faqsUpdated: number
  faqsMarkedOutdated: number

  // Changes detected
  contentChanged: boolean

  // Errors
  errors: string[]
  warnings: string[]
}
